name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    os: [ubuntu-latest, windows-latest, macOS-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: generate
      run: cmake . -B.build
    - name: compile
      run: cmake --build .build
    - name: unit test
      run: ctest .build
