name: CMake Pipeline
on: [push]
env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v1
      with: 
        fetch-depth: 1

    - name: Setup build environment
      shell: bash
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Install dependencies
      if: matrix.os == 'ubuntu-latest'
      shell: bash
      run: sudo apt-get install libx11-dev xorg-dev freeglut3-dev libudev-dev

    - name: Generate project
      shell: bash
      env:
        SOURCE_DIR: ${{runner.workspace}}
      working-directory: ${{runner.workspace}}/build
      run: cmake $SOURCE_DIR -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build project
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Run unit tests
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ctest -C $BUILD_TYPE