name: CMake Pipeline
on: [push]
env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
      with: 
        fetch-depth: 1
        
    - name: Create build directory
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Install dependencies
      if: matrix.os == 'ubuntu-latest'
      run: | 
        sudo apt-get install libx11-dev 
        sudo apt-get install xorg-dev 
        sudo apt-get install freeglut3-dev 
        sudo apt-get install libudev-dev
      shell: bash

    - name: Generate project
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
      shell: bash

    - name: Build project
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --config $BUILD_TYPE
      shell: bash

    - name: Run unit tests
      working-directory: ${{runner.workspace}}/build
      run: ctest -C $BUILD_TYPE
      shell: bash